name = "MyCertifiedCompiler"
version = "0.1.0"
defaultTargets = ["MyCertifiedCompiler", "certifiedcompiler"]

[[lean_lib]]
name = "MyCertifiedCompiler"

[[lean_exe]]
name = "certifiedcompiler"
root = "Main"

