name = "BaseVerifiedCompiler"
version = "0.1.0"
defaultTargets = ["BaseVerifiedCompiler", "ConditionalVerifiedCompiler", "verifiedcompiler"]

[[lean_lib]]
name = "BaseVerifiedCompiler"

[[lean_lib]]
name = "ConditionalVerifiedCompiler"

[[lean_exe]]
name = "verifiedcompiler"
root = "Main"
